version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - "@babel/*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
      react:
        patterns:
          - "react"
          - "react-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
