services:
  - type: web
    name: zoterpile
    runtime: python
    plan: free
    buildCommand: pip install -e .
    startCommand: zoterpile-web
    envVars:
      - key: ZOTERPILE_API_KEY
        generateValue: true
      - key: RENDER
        value: "true"
